pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout repo
                checkout scm
                // Show git branch (credentials check)
                sh 'git branch'
            }
        }

        stage('Install dependencies') {
            steps {
                sh 'pip install --upgrade pip'
                sh 'pip install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest --maxfail=1 --disable-warnings -q --junitxml=report.xml'
            }
        }
    }

    post {
        always {
            junit 'report.xml'
        }
    }
}
