pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/George-1999-os/alx-backend-python.git'
            }
        }

        stage('Check Credentials') {
            steps {
                sh 'git branch'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip3 install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest --maxfail=1 --disable-warnings -q'
            }
        }
    }
}
