# Generated by Django 5.2.4 on 2025-11-30 23:41

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0015_notification'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('unread', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
