pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/George-1999-os/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'python3 -m venv venv'
                sh '. venv/bin/activate && pip install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh '. venv/bin/activate && pytest --junitxml=report.xml messaging_app/tests'
            }
        }

        stage('Archive Report') {
            steps {
                junit 'report.xml'
            }
        }
    }
}
