#!/usr/bin/env bash

# Parse Pokémon data
JSON_FILE="pokemon_data/pikachu.json"

NAME=$(jq -r '.name' "$JSON_FILE" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')
HEIGHT=$(jq -r '.height' "$JSON_FILE")
WEIGHT=$(jq -r '.weight' "$JSON_FILE")
TYPE=$(jq -r '.types[0].type.name' "$JSON_FILE" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')

echo "$NAME is of type $TYPE, weighs ${WEIGHT}kg, and is ${HEIGHT}m tall."
